apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # these labels are expense resources
  labels:
    app: frontend
    tier: frontend
    project: expense
spec:
# modify replicas according to your case
  replicas: 1
  selector:
  # replicaset use these labels to find the pods for creating desired number of replicas
    matchLabels:
     app: frontend
     tier: frontend
     project: expense
  # pod template
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:   
      containers:
      - name: nginx
        image: ayeshacs540/frontend:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec: 
type: LoadBalancer
  selector: #labels arre used as selectors
        app: frontend
        tier: web
        project: expense 
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port number
