apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # these labels are expense resources
  labels:
    app: mysql
    tier: mysql
    purpose: expense
spec:
# modify replicas according to your case
  replicas: 1
  selector:
  # replicaset use these labels to find the pods for creating desired number of replicas
    matchLabels:
     app: mysql
     tier: mysql
     purpose: expense
  # pod template
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        purpose: expense
    spec:   
      containers:
      - name: nginx
        image: ayeshacs540/expense:1.0
        